% Cannabis leaf — botanically improved
% 7 lanceolate leaflets, each with midrib + lateral veins
% Demonstrates: patch, polyshape, rotation transforms, subplot-free figure layout
% 4.20.2026 | MATLAB for EEG Scientists
%
% Code largely generated by Claude Sonnet 4.6, prompted by John Allen, and
% final corrections by John Allen 

clear; close all; clc;

figure('Color','w','Position',[100 80 620 680]);
ax = axes('Position',[0.05 0.08 0.9 0.88]);
hold on; axis equal off;
xlim([-200 200]); ylim([-130 230]);



%% --- Leaflet parameters: [angle_deg, length, width, n_serrations, color_rgb] ---
leaflets = {
%  angle  len   wid  serr  color
   0,     175,  22,  11,  [0.20 0.55 0.15];   % center (main)
   38,    140,  18,  9,   [0.24 0.60 0.18];   % upper-right
  -38,    140,  18,  9,   [0.24 0.60 0.18];   % upper-left
   76,    108,  14,  7,   [0.30 0.65 0.22];   % mid-right
  -76,    108,  14,  7,   [0.30 0.65 0.22];   % mid-left
  112,     72,  10,  5,   [0.36 0.70 0.26];   % lower-right
 -112,     72,  10,  5,   [0.36 0.70 0.26];   % lower-left
};

%% --- Draw leaflets ---
for i = 1:size(leaflets,1)
    row   = leaflets(i,:);
    ang   = row{1};  len = row{2};  wid = row{3};
    nserr = row{4};  col = row{5};

    [xL, yL] = make_leaflet(len, wid, nserr);

    % Rotate about origin
    ang_r = deg2rad(ang);
    R = [cos(ang_r) -sin(ang_r); sin(ang_r) cos(ang_r)];
    pts = R * [xL; yL];

    patch(pts(1,:), pts(2,:), col, ...
        'EdgeColor', col*0.6, 'LineWidth', 0.6, 'FaceAlpha', 0.92);

    % --- Midrib ---
    midrib_pts = R * [zeros(1,60); linspace(2, len*0.97, 60)];
    plot(midrib_pts(1,:), midrib_pts(2,:), '-', ...
        'Color', col*0.55, 'LineWidth', 1.0);

    % --- Lateral veins (pairs along midrib) ---
    n_pairs = floor(nserr / 2);
    for v = 1:n_pairs
        t_v = 0.12 + (v / (n_pairs+1)) * 0.72;
        base_pt = R * [0; t_v * len];
        vein_len = wid * (1 - t_v) * 1.8;
        vein_ang = ang_r + deg2rad(55);   % right vein
        tip_r = base_pt + vein_len * [cos(vein_ang - pi/2); sin(vein_ang - pi/2)];
        tip_l = base_pt + vein_len * [cos(vein_ang + pi/2 + deg2rad(20)); sin(vein_ang + pi/2 + deg2rad(20))];

        % Curve the veins slightly using 3-pt interpolation
        for tip = {tip_r, tip_l}
            tip = tip{1};
            tvec = linspace(0,1,20);
            mid_ctrl = (base_pt + tip)/2 + R*[wid*0.08*(2*(rand>0.5)-1); 0];
            vx = (1-tvec).^2 * base_pt(1) + 2*(1-tvec).*tvec * mid_ctrl(1) + tvec.^2 * tip(1);
            vy = (1-tvec).^2 * base_pt(2) + 2*(1-tvec).*tvec * mid_ctrl(2) + tvec.^2 * tip(2);
            plot(vx, vy, '-', 'Color', col*0.55, 'LineWidth', 0.55);
        end
    end
end

%% --- Petiole (stem) ---
t_s = linspace(0, 1, 80);
stem_x = 3 * sin(t_s * pi * 0.4);
stem_y = -t_s * 110;
patch([stem_x - 2.5, fliplr(stem_x + 2.5)], ...
      [stem_y,       fliplr(stem_y)], ...
      [0.22 0.48 0.12], 'EdgeColor','none', 'FaceAlpha', 0.95);

%% --- Title & annotation ---
title('Cannabis sativa — 7-leaflet palmate compound leaf', ...
    'FontSize', 12, 'FontWeight', 'normal', 'Color', [0.15 0.40 0.08]);
text(0, -118, '4.20.2026  |  MATLAB for EEG Scientists', ...
    'HorizontalAlignment','center','FontSize',8.5,...
    'Color',[0.55 0.55 0.55],'FontAngle','italic');

%% --- Leaflet shape generator ---
% Returns x,y of a serrated lanceolate leaflet pointing up, centered at origin
function [xL, yL] = make_leaflet(len, wid, n_serrations)
    % Right edge (base to tip)
    t_r = linspace(0, 1, 200);
    % Width profile: broad in lower third, tapers to tip
    w_r = wid .* t_r .* (1 - t_r.^1.4) .* 3.2;
    y_r = t_r * len;

    % Add serrations on right edge
    n_s = n_serrations;
    serr_amp = wid * 0.10;
    serr = serr_amp .* max(0, sin(t_r * pi * n_s * 2)) .* (1 - t_r).^0.5;
    x_r = w_r + serr;

    % Mirror for left edge (flipped serration phase for asymmetry)
    serr_l = serr_amp .* max(0, sin(t_r * pi * n_s * 2 + pi*0.7)) .* (1 - t_r).^0.5;
    x_l = -(w_r + serr_l);

    % Combine: base -> right edge up -> tip -> left edge down -> base
    xL = [0, x_r, 0, fliplr(x_l), 0];
    yL = [0, y_r, len, fliplr(y_r), 0];
end