% Cannabis leaf — botanically improved, with per-run variation
% 7 lanceolate leaflets, each with midrib + lateral veins
% Demonstrates: patch, rotation transforms, Bezier curves, rng, print/saveas
% 4.20.2026 | MATLAB for EEG Scientists
%
% Code largely generated by Claude Sonnet 4.6, prompted by John Allen, and
% final corrections by John Allen 

clear; close all; clc;

%% --- Seed control ---
% Set FIXED_SEED to a positive integer to reproduce a specific leaf.
% Set FIXED_SEED = [] to shuffle — a new leaf every run.
FIXED_SEED = [];

if isempty(FIXED_SEED)
    rng('shuffle');
else
    rng(FIXED_SEED);
end
rng_state = rng;
fprintf('RNG seed this run: %d\n', rng_state.Seed);

%% --- Global shape variation ---
% These scalars vary the whole-leaf character each run
overall_scale = 0.85 + 0.30 * rand;          % leaf size (0.85 - 1.15)
lean          = (rand - 0.5) * 18;            % whole-leaf lean, degrees (-9 to +9)
color_shift   = (rand - 0.5) * 0.08;          % global brightness offset

%% --- Figure setup ---
fig = figure('Color','w','Position',[100 80 620 680]);
ax  = axes('Position',[0.05 0.08 0.9 0.88]);
hold on; axis equal off;
xlim([-220 220]); ylim([-140 250]);

%% --- Leaflet base parameters ---
% Columns: base_angle | base_len | base_wid | base_serr | base_color
base = {
%  angle   len   wid  serr  color
   0,      175,  22,  11,  [0.20 0.55 0.15];   % center
   38,     140,  18,   9,  [0.24 0.60 0.18];   % upper-right
  -38,     140,  18,   9,  [0.24 0.60 0.18];   % upper-left
   76,     108,  14,   7,  [0.30 0.65 0.22];   % mid-right
  -76,     108,  14,   7,  [0.30 0.65 0.22];   % mid-left
  112,      72,  10,   5,  [0.36 0.70 0.26];   % lower-right
 -112,      72,  10,   5,  [0.36 0.70 0.26];   % lower-left
};

n_leaflets = size(base, 1);

% Per-leaflet random perturbations (computed once, before drawing loop)
angle_jitter  = (rand(n_leaflets,1) - 0.5) * 10;    % +/- 5 deg per leaflet
len_scale     = 0.82 + 0.36 * rand(n_leaflets,1);   % 0.82 - 1.18
wid_scale     = 0.80 + 0.40 * rand(n_leaflets,1);   % 0.80 - 1.20
serr_jitter   = round((rand(n_leaflets,1) - 0.5)*4); % +/- 2 serrations
color_jitter  = (rand(n_leaflets,3) - 0.5) * 0.10;  % per-channel +/- 0.05
serr_amp_mult = 0.6 + 0.8 * rand(n_leaflets,1);     % serration depth 0.6-1.4x

% Enforce bilateral symmetry: mirror jitter for paired leaflets (2&3, 4&5, 6&7)
pairs = [2 3; 4 5; 6 7];
for p = 1:size(pairs,1)
    L = pairs(p,1);  R = pairs(p,2);
    shared_ang = (angle_jitter(L) + angle_jitter(R)) / 2;
    angle_jitter(L) = shared_ang;
    angle_jitter(R) = shared_ang;
    shared_len = (len_scale(L) + len_scale(R)) / 2;
    len_scale(L) = shared_len;  len_scale(R) = shared_len;
    shared_wid = (wid_scale(L) + wid_scale(R)) / 2;
    wid_scale(L) = shared_wid;  wid_scale(R) = shared_wid;
    shared_col = (color_jitter(L,:) + color_jitter(R,:)) / 2;
    color_jitter(L,:) = shared_col;
    color_jitter(R,:) = shared_col;
end

%% --- Draw leaflets ---
for i = 1:n_leaflets
    row   = base(i,:);
    ang   = row{1} + angle_jitter(i) + lean;
    len   = row{2} * len_scale(i)   * overall_scale;
    wid   = row{3} * wid_scale(i)   * overall_scale;
    nserr = max(3, row{4} + serr_jitter(i));
    col   = clamp01(row{5} + color_jitter(i,:) + color_shift);

    [xL, yL] = make_leaflet(len, wid, nserr, serr_amp_mult(i));

    ang_r = deg2rad(ang);
    R = [cos(ang_r) -sin(ang_r); sin(ang_r) cos(ang_r)];
    pts = R * [xL; yL];

    patch(pts(1,:), pts(2,:), col, ...
        'EdgeColor', col*0.6, 'LineWidth', 0.6, 'FaceAlpha', 0.92);

    % Midrib
    midrib_pts = R * [zeros(1,60); linspace(2, len*0.97, 60)];
    plot(midrib_pts(1,:), midrib_pts(2,:), '-', ...
        'Color', col*0.55, 'LineWidth', 1.0);

    % Lateral veins -- quadratic Bezier with random control-point jitter
    n_pairs = floor(nserr / 2);
    for v = 1:n_pairs
        t_v      = 0.12 + (v / (n_pairs+1)) * 0.72;
        base_pt  = R * [0; t_v * len];
        vein_len = wid * (1 - t_v) * 1.8;
        vein_ang = ang_r + deg2rad(50 + rand*15);    % vein angle varies 50-65 deg
        tip_r    = base_pt + vein_len * [cos(vein_ang - pi/2); sin(vein_ang - pi/2)];
        tip_l    = base_pt + vein_len * [cos(vein_ang + pi/2 + deg2rad(15 + rand*10)); ...
                                          sin(vein_ang + pi/2 + deg2rad(15 + rand*10))];
        for tip = {tip_r, tip_l}
            tip      = tip{1};
            tvec     = linspace(0, 1, 20);
            jitter   = wid * 0.10 * (2*(rand > 0.5) - 1);
            mid_ctrl = (base_pt + tip)/2 + R*[jitter; 0];
            vx = (1-tvec).^2*base_pt(1) + 2*(1-tvec).*tvec*mid_ctrl(1) + tvec.^2*tip(1);
            vy = (1-tvec).^2*base_pt(2) + 2*(1-tvec).*tvec*mid_ctrl(2) + tvec.^2*tip(2);
            plot(vx, vy, '-', 'Color', col*0.55, 'LineWidth', 0.55);
        end
    end
end

%% --- Petiole (stem) ---
t_s      = linspace(0, 1, 80);
lean_amt = (rand - 0.5) * 8;
stem_x   = lean_amt * t_s + 4 * sin(t_s * pi * (0.3 + rand*0.3));
stem_y   = -t_s * (95 + rand*30);
stem_col = clamp01([0.22 0.48 0.12] + (rand(1,3)-0.5)*0.06);
patch([stem_x - 2.5, fliplr(stem_x + 2.5)], ...
      [stem_y,        fliplr(stem_y)], ...
      stem_col, 'EdgeColor','none', 'FaceAlpha', 0.95);

%% --- Title & annotation ---
title('Cannabis sativa -- 7-leaflet palmate compound leaf', ...
    'FontSize', 12, 'FontWeight', 'normal', 'Color', [0.15 0.40 0.08]);
text(0, -128, sprintf('4.20.2026  |  MATLAB for EEG Scientists  |  seed: %d', rng_state.Seed), ...
    'HorizontalAlignment','center','FontSize',8.5,...
    'Color',[0.55 0.55 0.55],'FontAngle','italic');

%% --- Export ---
out_png = sprintf('Four20_seed%d.png', rng_state.Seed);
print(fig, out_png, '-dpng', '-r300');
fprintf('Figure saved: %s\n', out_png);

% Uncomment to also save as vector PDF:
% print(fig, sprintf('Four20_seed%d.pdf', rng_state.Seed), '-dpdf');

%% =========================================================
%% Local functions -- must remain below all script code
%% =========================================================

function [xL, yL] = make_leaflet(len, wid, n_serrations, serr_amp_mult)
% MAKE_LEAFLET  Generate x,y outline of a serrated lanceolate leaflet.
%   Points upward (+y), centered at origin.
%   Inputs:
%     len           -- leaflet length
%     wid           -- maximum half-width
%     n_serrations  -- number of teeth per margin
%     serr_amp_mult -- serration depth multiplier (0.6-1.4)

    t_r = linspace(0, 1, 200);
    w_r = wid .* t_r .* (1 - t_r.^1.4) .* 3.2;
    y_r = t_r * len;

    serr_amp = wid * 0.10 * serr_amp_mult;
    serr_r   = serr_amp .* max(0, sin(t_r * pi * n_serrations * 2))          .* (1-t_r).^0.5;
    serr_l   = serr_amp .* max(0, sin(t_r * pi * n_serrations * 2 + pi*0.7)) .* (1-t_r).^0.5;

    x_r =  w_r + serr_r;
    x_l = -(w_r + serr_l);

    xL = [0,  x_r,  0, fliplr(x_l), 0];
    yL = [0,  y_r, len, fliplr(y_r), 0];
end

function c = clamp01(c)
% CLAMP01  Clamp RGB values to [0,1] to avoid invalid color errors.
    c = min(1, max(0, c));
end